# App Info
ios_app_id                                :

appstore_link                             :
playstore_link                            : com.origamestudio.memorizekana
presskit_download_link                    :

app_icon                                  : assets/appicon.png
app_name                                  : Memorize Kana
app_price                                 : Free
app_description                           : Have fun studying Japanese! <br> Play this memory game to learn Hiragana and Katakana

enable_smart_app_banner                   : true



# Information About Yourself
your_name                                 : Guillermo Calvo
your_link                                 : https://guillermo.dev/
your_city                                 : Tokyo
email_address                             : origame-studio@guillermo.dev
facebook_username                         :
instagram_username                        : guillermocalvo
twitter_username                          : gcalvo
github_username                           : guillermocalvo
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Fun
    description                           : >
      Learn by matching up <strong>Hiragana</strong> and
      <strong>Katakana</strong> characters and <strong>Romaji</strong>.
    fontawesome_icon_name                 : gamepad

  - title                                 : Free
    description                           : >
      Download this <strong>free game</strong> and start learning Japanese
      language now.
    fontawesome_icon_name                 : yen-sign

  - title                                 : Game Modes
    description                           : >
      Select between <strong>three game modes</strong>, depending on the
      syllabary you want to study.
    fontawesome_icon_name                 : language

  - title                                 : Difficulty
    description                           : >
      Increase the difficulty level as you improve your skills:
      <strong>Easy</strong>, <strong>Medium</strong>, and <strong>Hard</strong>.
    fontawesome_icon_name                 : torii-gate

  - title                                 : Hints
    description                           : >
      Learn the characters you don't know yet by hearing
      <strong>how to pronounce</strong> each syllable.
    fontawesome_icon_name                 : lightbulb

  - title                                 : Music
    description                           : >
      Enjoy amazing music tracks by <a href="http://www.thekyotoconnection.com/">The Kyoto Connection</a>,
      <a href="https://www.jamendo.com/artist/357163/ambient-samurai-ichiro-nakagawa">Ambient Samurai</a>,
      and <a href="https://ozzed.net/">Ozzed</a>.
    fontawesome_icon_name                 : music


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
